# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: GitHubActions

env:
  APPLICATION_NAME: "YouTube Client"
  DEPLOY_PACKAGE_NAME: "youtube-client-ver-${{ github.sha }}"

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  clone_repo:
    runs-on: ubuntu-latest
    
    steps:
      - name: List current folder 
        run: ls -la
        
      - name: clone repo
        uses: action/chekout@v1
     
  install:
    runs-on: ubuntu-latest
    needs: [clone_repo]
     
    steps:
      - name: List current folder 
        run: ls -la

      - name: install packages
        run : echo "installing packages"
    
  test:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - name: run tests
        run: echo "running tests ${{ env.DEPLOY_PACKAGE_NAME }}"
